---
apiVersion: "v2"
name: "hedgedoc"
description: "A lightweight Helm chart for HedgeDoc that prioritizes transparency and flexibility"
type: "application"
icon: "https://avatars.githubusercontent.com/u/67865462"
keywords:
  - "hedgedoc"
  - "codimd"
  - "markdown"
  - "editor"
maintainers:
  - name: "ernail"
    email: "nagel.eric.95@googlemail.com"
annotations:
  artifacthub.io/license: "MIT"
  artifacthub.io/links: |
    - name: source
      url: https://github.com/erNail/hedgedoc-chart
    - name: support
      url: https://github.com/erNail/hedgedoc-chart/issues
version: "0.0.0"
# renovate: image=quay.io/hedgedoc/hedgedoc
appVersion: "1.10.5"
